services:
  - type: web
    name: theschoolrun
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PUBLIC_BASE_URL
        value: https://theschoolrun.xo.je
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
